# Generated by Django 6.0 on 2026-01-14 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('guest_count', models.IntegerField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('venue_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('services', models.TextField(blank=True, help_text='Comma separated list of services', null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('stage_decor', models.BooleanField(default=False)),
                ('flower_decor', models.BooleanField(default=False)),
                ('lighting_style', models.BooleanField(default=False)),
                ('food_type', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photography', models.CharField(blank=True, max_length=50, null=True)),
                ('videography', models.CharField(blank=True, max_length=50, null=True)),
                ('drone_shoot', models.CharField(blank=True, max_length=50, null=True)),
                ('seating_style', models.CharField(blank=True, max_length=100, null=True)),
                ('security', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('total_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
