# Generated by Django 6.0 on 2026-01-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
