# Generated by Django 6.0 on 2026-01-23 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_screen_seat_show_enhancedbooking_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(help_text='Short title or caption', max_length=100)),
                ('category', models.CharField(choices=[('wedding', 'Weddings'), ('corporate', 'Corporate'), ('concert', 'Concerts'), ('parties', 'Parties')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
