# Generated by Django 6.0 on 2026-02-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testimonial_created_at_testimonial_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
