# Generated by Django 6.0 on 2026-02-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
