# Generated by Django 6.0 on 2026-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_event_category_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['show', 'seat'], name='core_seatbo_show_id_7bf039_idx'),
        ),
    ]
