# Generated by Django 6.0 on 2026-02-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_package_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
