# Generated by Django 6.0 on 2026-02-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='seatbooking',
            name='core_seatbo_show_id_7bf039_idx',
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.RemoveField(
            model_name='enhancedbooking',
            name='show',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='show',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='show',
            name='event',
        ),

        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='show',
        ),
        migrations.DeleteModel(
            name='EnhancedBooking',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='SeatBooking',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
