# Generated by Django 6.0 on 2026-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_customevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(blank=True, help_text='Custom Event Name if applicable', max_length=200, null=True),
        ),
    ]
