# Generated by Django 6.0 on 2026-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_booking_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
