# Generated by Django 6.0 on 2026-02-17 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_customsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
