# Generated by Django 6.0 on 2026-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_customsession_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='session_data',
        ),
        migrations.AlterField(
            model_name='customsession',
            name='expire_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session_key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
